### PR TITLE
Supply default compiler optimization for ARM 

### PR DESCRIPTION
**Pull request by lordnynex**
Fixes openresty/ngx_openresty#83

### CODE REVIEW

**Comment by agentzh** [comment]
@lordnynex It seems like a C compiler bug. Disabling optimizations on all POSIX ARM systems look rather overkill to me. Is there a better way to test if the C compiler is indeed buggy under `-O2` or `-O1`?

**Comment by agentzh** [comment]
@lordnynex I've asked @yangshuxin to have a look on his Raspberry box.

**Comment by lordnynex** [comment]
@agentzh I will need to setup a test environment to explore this further. I wonder if it is specific to the Raspberry Pi version. My assumption was that openresty is not widely used on other ARM platforms but I could be wrong. 

I will try to test the build as soon as I can get the hardware together.

**Comment by agentzh** [comment]
@lordnynex That's cool. `-O0` can lead to a big loss in performance and I hope we can have optimizations enabled even on Raspberry Pi :)

**Comment by sparvu** [comment]
We have a dedicated environment running OpenResty on ARM so we can test, if needed. We have encounter this issue: https://groups.google.com/forum/#!topic/openresty-en/cI7qiuq-RdQ

2015/02/02 14:57:05 [notice] 6456#0: using the "epoll" event method
2015/02/02 14:57:05 [notice] 6456#0: openresty/1.7.7.1
2015/02/02 14:57:05 [notice] 6456#0: built by gcc 4.6.3 (Debian 
4.6.3-14+rpi1)
2015/02/02 14:57:05 [notice] 6456#0: OS: Linux 3.12.22+
2015/02/02 14:57:05 [notice] 6456#0: getrlimit(RLIMIT_NOFILE): 1024:4096
2015/02/02 14:57:05 [notice] 6457#0: start worker processes
2015/02/02 14:57:05 [notice] 6457#0: start worker process 6458
...
2015/02/02 14:58:06 [notice] 6457#0: signal 17 (SIGCHLD) received
2015/02/02 14:58:06 [alert] 6457#0: worker process 6458 exited on signal 7
...

**Comment by lordnynex** [comment]
@sparvu Can you test for this error with the following builds:

./configure --with-cc-opt="-O1"
and
./configure --with-cc-opt="-O2"

**Comment by sparvu** [comment]
Will do that. I will rebuild our builds with -O1. Later on details.

**Comment by agentzh** [comment]
@sparvu It'll be great if you can use gdb to get the full backtrace at the crashing site in the nginx worker process.

**Comment by sparvu** [comment]
-O1 seems same thing as -O2:

2015/02/05 21:21:21 [alert] 7006#0: worker process 7007 exited on signal 7
2015/02/05 21:21:21 [alert] 7006#0: shared memory zone "timer_locks" was locked by 7007

and trying to put gdb on worker, returned these:

Program received signal SIGBUS, Bus error.
0x000b4504 in ngx_http_lua_shdict_get_helper (L=0xb6ad6c48, get_stale=0)
    at ../ngx_lua-0.9.14/src/ngx_http_lua_shdict.c:486
486	../ngx_lua-0.9.14/src/ngx_http_lua_shdict.c: No such file or directory.

**Comment by agentzh** [comment]
@sparvu Will you type the gdb command "disas" to get the machine code dump around the PC?

**Comment by sparvu** [comment]
I hope I did capture all sequences:

Program received signal SIGBUS, Bus error.
0x000b4504 in ngx_http_lua_shdict_get_helper (L=0xb6a2ec48, get_stale=0) at ../ngx_lua-0.9.14/src/ngx_http_lua_shdict.c:486
486	../ngx_lua-0.9.14/src/ngx_http_lua_shdict.c: No such file or directory.
(gdb) disas
```
Dump of assembler code for function ngx_http_lua_shdict_get_helper:
   0x000b42d4 <+0>:	push	{r4, r5, r6, r7, r8, r10, lr}
   0x000b42d8 <+4>:	sub	sp, sp, #36	; 0x24
   0x000b42dc <+8>:	mov	r4, r0
   0x000b42e0 <+12>:	mov	r5, r1
   0x000b42e4 <+16>:	bl	0x1dab8
   0x000b42e8 <+20>:	mov	r2, r0
   0x000b42ec <+24>:	cmp	r0, #2
   0x000b42f0 <+28>:	beq	0xb4304 <ngx_http_lua_shdict_get_helper+48>
   0x000b42f4 <+32>:	mov	r0, r4
   0x000b42f8 <+36>:	ldr	r1, [pc, #764]	; 0xb45fc <ngx_http_lua_shdict_get_helper+808>
   0x000b42fc <+40>:	bl	0x1de90 <OCSP_RESPONSE_new+480>
   0x000b4300 <+44>:	b	0xb45f4 <ngx_http_lua_shdict_get_helper+800>
   0x000b4304 <+48>:	mov	r0, r4
   0x000b4308 <+52>:	mov	r1, #1
   0x000b430c <+56>:	bl	0x1d284
   0x000b4310 <+60>:	subs	r6, r0, #0
   0x000b4314 <+64>:	bne	0xb4328 <ngx_http_lua_shdict_get_helper+84>
   0x000b4318 <+68>:	mov	r0, r4
   0x000b431c <+72>:	ldr	r1, [pc, #732]	; 0xb4600 <ngx_http_lua_shdict_get_helper+812>
   0x000b4320 <+76>:	bl	0x1de90 <OCSP_RESPONSE_new+480>
   0x000b4324 <+80>:	b	0xb45f4 <ngx_http_lua_shdict_get_helper+800>
   0x000b4328 <+84>:	ldr	r7, [r6]
   0x000b432c <+88>:	add	r3, r7, #8
   0x000b4330 <+92>:	ldm	r3, {r0, r1}
   0x000b4334 <+96>:	add	r3, sp, #32
   0x000b4338 <+100>:	stmdb	r3, {r0, r1}
   0x000b433c <+104>:	mov	r0, r4
   0x000b4340 <+108>:	mov	r1, #2
   0x000b4344 <+112>:	bl	0x1d9ec
   0x000b4348 <+116>:	cmp	r0, #0
   0x000b434c <+120>:	bne	0xb4370 <ngx_http_lua_shdict_get_helper+156>
   0x000b4350 <+124>:	mov	r0, r4
---Type <return> to continue, or q <return> to quit---
   0x000b4354 <+128>:	bl	0x1df44 <OCSP_RESPONSE_new+660>
   0x000b4358 <+132>:	mov	r0, r4
   0x000b435c <+136>:	ldr	r1, [pc, #672]	; 0xb4604 <ngx_http_lua_shdict_get_helper+816>
   0x000b4360 <+140>:	mov	r2, #7
   0x000b4364 <+144>:	bl	0x1de78 <OCSP_RESPONSE_new+456>
   0x000b4368 <+148>:	mov	r0, #2
   0x000b436c <+152>:	b	0xb45f4 <ngx_http_lua_shdict_get_helper+800>
   0x000b4370 <+156>:	mov	r0, r4
   0x000b4374 <+160>:	mov	r1, #2
   0x000b4378 <+164>:	add	r2, sp, #16
   0x000b437c <+168>:	bl	0x1d230
   0x000b4380 <+172>:	str	r0, [sp, #20]
   0x000b4384 <+176>:	ldr	r3, [sp, #16]
   0x000b4388 <+180>:	cmp	r3, #0
   0x000b438c <+184>:	bne	0xb43b0 <ngx_http_lua_shdict_get_helper+220>
   0x000b4390 <+188>:	mov	r0, r4
   0x000b4394 <+192>:	bl	0x1df44 <OCSP_RESPONSE_new+660>
   0x000b4398 <+196>:	mov	r0, r4
   0x000b439c <+200>:	ldr	r1, [pc, #612]	; 0xb4608 <ngx_http_lua_shdict_get_helper+820>
   0x000b43a0 <+204>:	mov	r2, #9
   0x000b43a4 <+208>:	bl	0x1de78 <OCSP_RESPONSE_new+456>
   0x000b43a8 <+212>:	mov	r0, #2
   0x000b43ac <+216>:	b	0xb45f4 <ngx_http_lua_shdict_get_helper+800>
   0x000b43b0 <+220>:	cmp	r3, #65536	; 0x10000
   0x000b43b4 <+224>:	ldrcc	r2, [pc, #592]	; 0xb460c <ngx_http_lua_shdict_get_helper+824>
   0x000b43b8 <+228>:	ldrcc	r1, [r2]
   0x000b43bc <+232>:	mvncc	r8, #0
   0x000b43c0 <+236>:	bcc	0xb43e4 <ngx_http_lua_shdict_get_helper+272>
   0x000b43c4 <+240>:	mov	r0, r4
   0x000b43c8 <+244>:	bl	0x1df44 <OCSP_RESPONSE_new+660>
   0x000b43cc <+248>:	mov	r0, r4
   0x000b43d0 <+252>:	ldr	r1, [pc, #568]	; 0xb4610 <ngx_http_lua_shdict_get_helper+828>
   0x000b43d4 <+256>:	mov	r2, #12
---Type <return> to continue, or q <return> to quit---
   0x000b43d8 <+260>:	bl	0x1de78 <OCSP_RESPONSE_new+456>
   0x000b43dc <+264>:	mov	r0, #2
   0x000b43e0 <+268>:	b	0xb45f4 <ngx_http_lua_shdict_get_helper+800>
   0x000b43e4 <+272>:	ldrb	r2, [r0], #1
   0x000b43e8 <+276>:	eor	r12, r8, r2
   0x000b43ec <+280>:	and	r12, r12, #15
   0x000b43f0 <+284>:	ldr	r12, [r1, r12, lsl #2]
   0x000b43f4 <+288>:	eor	r8, r12, r8, lsr #4
   0x000b43f8 <+292>:	eor	r2, r8, r2, lsr #4
   0x000b43fc <+296>:	and	r2, r2, #15
   0x000b4400 <+300>:	ldr	r2, [r1, r2, lsl #2]
   0x000b4404 <+304>:	eor	r8, r2, r8, lsr #4
   0x000b4408 <+308>:	subs	r3, r3, #1
   0x000b440c <+312>:	bne	0xb43e4 <ngx_http_lua_shdict_get_helper+272>
   0x000b4410 <+316>:	mvn	r8, r8
   0x000b4414 <+320>:	ldr	r0, [r7, #4]
   0x000b4418 <+324>:	add	r0, r0, #44	; 0x2c
   0x000b441c <+328>:	bl	0x29ff4 <ngx_shmtx_lock>
   0x000b4420 <+332>:	cmp	r5, #0
   0x000b4424 <+336>:	bne	0xb4434 <ngx_http_lua_shdict_get_helper+352>
   0x000b4428 <+340>:	mov	r0, r7
   0x000b442c <+344>:	mov	r1, #1
   0x000b4430 <+348>:	bl	0xb3068 <ngx_http_lua_shdict_expire>
   0x000b4434 <+352>:	add	r3, sp, #12
   0x000b4438 <+356>:	str	r3, [sp]
   0x000b443c <+360>:	mov	r0, r6
   0x000b4440 <+364>:	mov	r1, r8
   0x000b4444 <+368>:	ldr	r2, [sp, #20]
   0x000b4448 <+372>:	ldr	r3, [sp, #16]
   0x000b444c <+376>:	bl	0xb3198 <ngx_http_lua_shdict_lookup>
   0x000b4450 <+380>:	mov	r6, r0
   0x000b4454 <+384>:	cmn	r0, #5
   0x000b4458 <+388>:	beq	0xb4468 <ngx_http_lua_shdict_get_helper+404>
---Type <return> to continue, or q <return> to quit---
   0x000b445c <+392>:	cmp	r5, #0
   0x000b4460 <+396>:	cmneq	r0, #4
   0x000b4464 <+400>:	bne	0xb4484 <ngx_http_lua_shdict_get_helper+432>
   0x000b4468 <+404>:	ldr	r0, [r7, #4]
   0x000b446c <+408>:	add	r0, r0, #44	; 0x2c
   0x000b4470 <+412>:	bl	0x2a1b4 <ngx_shmtx_unlock>
   0x000b4474 <+416>:	mov	r0, r4
   0x000b4478 <+420>:	bl	0x1df44 <OCSP_RESPONSE_new+660>
   0x000b447c <+424>:	mov	r0, #1
   0x000b4480 <+428>:	b	0xb45f4 <ngx_http_lua_shdict_get_helper+800>
   0x000b4484 <+432>:	ldr	r2, [sp, #12]
   0x000b4488 <+436>:	ldrb	r8, [r2, #24]
   0x000b448c <+440>:	ldrh	r0, [r2, #2]
   0x000b4490 <+444>:	add	r3, r0, #32
   0x000b4494 <+448>:	add	r3, r2, r3
   0x000b4498 <+452>:	add	r1, r3, #4
   0x000b449c <+456>:	ldr	r10, [r2, #28]
   0x000b44a0 <+460>:	cmp	r8, #3
   0x000b44a4 <+464>:	beq	0xb44cc <ngx_http_lua_shdict_get_helper+504>
   0x000b44a8 <+468>:	cmp	r8, #4
   0x000b44ac <+472>:	beq	0xb44bc <ngx_http_lua_shdict_get_helper+488>
   0x000b44b0 <+476>:	cmp	r8, #1
   0x000b44b4 <+480>:	bne	0xb4558 <ngx_http_lua_shdict_get_helper+644>
   0x000b44b8 <+484>:	b	0xb450c <ngx_http_lua_shdict_get_helper+568>
   0x000b44bc <+488>:	mov	r0, r4
   0x000b44c0 <+492>:	mov	r2, r10
   0x000b44c4 <+496>:	bl	0x1de78 <OCSP_RESPONSE_new+456>
   0x000b44c8 <+500>:	b	0xb4580 <ngx_http_lua_shdict_get_helper+684>
   0x000b44cc <+504>:	cmp	r10, #8
   0x000b44d0 <+508>:	beq	0xb44fc <ngx_http_lua_shdict_get_helper+552>
   0x000b44d4 <+512>:	ldr	r0, [r7, #4]
   0x000b44d8 <+516>:	add	r0, r0, #44	; 0x2c
   0x000b44dc <+520>:	bl	0x2a1b4 <ngx_shmtx_unlock>
---Type <return> to continue, or q <return> to quit---
   0x000b44e0 <+524>:	str	r10, [sp]
   0x000b44e4 <+528>:	mov	r0, r4
   0x000b44e8 <+532>:	ldr	r1, [pc, #292]	; 0xb4614 <ngx_http_lua_shdict_get_helper+832>
   0x000b44ec <+536>:	ldr	r2, [sp, #20]
   0x000b44f0 <+540>:	ldr	r3, [sp, #28]
   0x000b44f4 <+544>:	bl	0x1de90 <OCSP_RESPONSE_new+480>
   0x000b44f8 <+548>:	b	0xb45f4 <ngx_http_lua_shdict_get_helper+800>
   0x000b44fc <+552>:	mov	r0, r4
   0x000b4500 <+556>:	vldr	d0, [r3, #4]
=> 0x000b4504 <+560>:	bl	0x1d128
   0x000b4508 <+564>:	b	0xb4580 <ngx_http_lua_shdict_get_helper+684>
   0x000b450c <+568>:	cmp	r10, #1
   0x000b4510 <+572>:	beq	0xb453c <ngx_http_lua_shdict_get_helper+616>
   0x000b4514 <+576>:	ldr	r0, [r7, #4]
   0x000b4518 <+580>:	add	r0, r0, #44	; 0x2c
   0x000b451c <+584>:	bl	0x2a1b4 <ngx_shmtx_unlock>
   0x000b4520 <+588>:	str	r10, [sp]
   0x000b4524 <+592>:	mov	r0, r4
   0x000b4528 <+596>:	ldr	r1, [pc, #232]	; 0xb4618 <ngx_http_lua_shdict_get_helper+836>
   0x000b452c <+600>:	ldr	r2, [sp, #20]
   0x000b4530 <+604>:	ldr	r3, [sp, #28]
   0x000b4534 <+608>:	bl	0x1de90 <OCSP_RESPONSE_new+480>
   0x000b4538 <+612>:	b	0xb45f4 <ngx_http_lua_shdict_get_helper+800>
   0x000b453c <+616>:	add	r2, r2, r0
   0x000b4540 <+620>:	ldrb	r1, [r2, #36]	; 0x24
   0x000b4544 <+624>:	mov	r0, r4
   0x000b4548 <+628>:	adds	r1, r1, #0
   0x000b454c <+632>:	movne	r1, #1
   0x000b4550 <+636>:	bl	0x1d9bc
   0x000b4554 <+640>:	b	0xb4580 <ngx_http_lua_shdict_get_helper+684>
   0x000b4558 <+644>:	ldr	r0, [r7, #4]
   0x000b455c <+648>:	add	r0, r0, #44	; 0x2c
   0x000b4560 <+652>:	bl	0x2a1b4 <ngx_shmtx_unlock>
---Type <return> to continue, or q <return> to quit---
   0x000b4564 <+656>:	str	r8, [sp]
   0x000b4568 <+660>:	mov	r0, r4
   0x000b456c <+664>:	ldr	r1, [pc, #168]	; 0xb461c <ngx_http_lua_shdict_get_helper+840>
   0x000b4570 <+668>:	ldr	r2, [sp, #20]
   0x000b4574 <+672>:	ldr	r3, [sp, #28]
   0x000b4578 <+676>:	bl	0x1de90 <OCSP_RESPONSE_new+480>
   0x000b457c <+680>:	b	0xb45f4 <ngx_http_lua_shdict_get_helper+800>
   0x000b4580 <+684>:	ldr	r3, [sp, #12]
   0x000b4584 <+688>:	ldr	r8, [r3, #32]
   0x000b4588 <+692>:	ldr	r0, [r7, #4]
   0x000b458c <+696>:	add	r0, r0, #44	; 0x2c
   0x000b4590 <+700>:	bl	0x2a1b4 <ngx_shmtx_unlock>
   0x000b4594 <+704>:	cmp	r5, #0
   0x000b4598 <+708>:	beq	0xb45d8 <ngx_http_lua_shdict_get_helper+772>
   0x000b459c <+712>:	cmp	r8, #0
   0x000b45a0 <+716>:	beq	0xb45b4 <ngx_http_lua_shdict_get_helper+736>
   0x000b45a4 <+720>:	mov	r0, r4
   0x000b45a8 <+724>:	mov	r1, r8
   0x000b45ac <+728>:	bl	0x1d194
   0x000b45b0 <+732>:	b	0xb45bc <ngx_http_lua_shdict_get_helper+744>
   0x000b45b4 <+736>:	mov	r0, r4
   0x000b45b8 <+740>:	bl	0x1df44 <OCSP_RESPONSE_new+660>
   0x000b45bc <+744>:	mov	r0, r4
   0x000b45c0 <+748>:	cmn	r6, #4
   0x000b45c4 <+752>:	movne	r1, #0
   0x000b45c8 <+756>:	moveq	r1, #1
   0x000b45cc <+760>:	bl	0x1d9bc
   0x000b45d0 <+764>:	mov	r0, #3
   0x000b45d4 <+768>:	b	0xb45f4 <ngx_http_lua_shdict_get_helper+800>
   0x000b45d8 <+772>:	cmp	r8, #0
   0x000b45dc <+776>:	moveq	r0, #1
   0x000b45e0 <+780>:	beq	0xb45f4 <ngx_http_lua_shdict_get_helper+800>
   0x000b45e4 <+784>:	mov	r0, r4
---Type <return> to continue, or q <return> to quit---
   0x000b45e8 <+788>:	mov	r1, r8
   0x000b45ec <+792>:	bl	0x1d194
   0x000b45f0 <+796>:	mov	r0, #2
   0x000b45f4 <+800>:	add	sp, sp, #36	; 0x24
   0x000b45f8 <+804>:	pop	{r4, r5, r6, r7, r8, r10, pc}
   0x000b45fc <+808>:	andeq	r10, lr, r4, lsl #6
   0x000b4600 <+812>:	andeq	r10, lr, r4, lsr #4
   0x000b4604 <+816>:	andeq	r10, lr, r8, lsr r2
   0x000b4608 <+820>:	andeq	r10, lr, r0, asr #4
   0x000b460c <+824>:	andeq	r6, pc, r0, ror #28
   0x000b4610 <+828>:	andeq	r10, lr, r12, asr #4
   0x000b4614 <+832>:	andeq	r10, lr, r8, lsr r3
   0x000b4618 <+836>:	andeq	r10, lr, r12, ror r3
   0x000b461c <+840>:	andeq	r10, lr, r0, asr #7
End of assembler dump.
```

**Comment by agentzh** [comment]
@sparvu Okay, @yangshuxin helped me nail down the real issue. It's a bug in ngx_lua which does not take alignment into account. I'll submit a patch soon. Thanks!

**Comment by sparvu** [comment]
sweet. if we have something as a new release anytime let me know to re-test.

**Comment by agentzh** [comment]
@sparvu Will you try the following patch on your side:

```diff
diff --git a/src/ngx_http_lua_shdict.c b/src/ngx_http_lua_shdict.c
index 377f9ce..8c666f7 100644
--- a/src/ngx_http_lua_shdict.c
+++ b/src/ngx_http_lua_shdict.c
@@ -481,7 +481,7 @@ ngx_http_lua_shdict_get_helper(lua_State *L, int get_stale)
                               (unsigned long) value.len);
         }
 
-        num = *(double *) value.data;
+        ngx_memcpy(&num, value.data, sizeof(double));
 
         lua_pushnumber(L, num);
         break;
@@ -1220,7 +1220,7 @@ ngx_http_lua_shdict_incr(lua_State *L)
 
     p = sd->data + key.len;
 
-    num = *(double *) p;
+    ngx_memcpy(&num, p, sizeof(double));
     num += value;
 
     ngx_memcpy(p, (double *) &num, sizeof(double));
@@ -1711,7 +1711,7 @@ ngx_http_lua_ffi_shdict_get(ngx_shm_zone_t *zone, u_char *key,
         }
 
         *str_value_len = value.len;
-        *num_value = *(double *) value.data;
+        ngx_memcpy(num_value, value.data, sizeof(double));
         break;
 
     case LUA_TBOOLEAN:
@@ -1801,7 +1801,7 @@ ngx_http_lua_ffi_shdict_incr(ngx_shm_zone_t *zone, u_char *key,
 
     p = sd->data + key_len;
 
-    num = *(double *) p;
+    ngx_memcpy(&num, p, sizeof(double));
     num += *value;
 
     ngx_memcpy(p, (double *) &num, sizeof(double));
```

We tried this patch with gcc -O2 on @yangshuxin's Raspberry Pi and it seems working.

Let me know if you run into any further problems. Thanks!

**Comment by sparvu** [comment]
The fix works without any problems. We will keep testing for coming days. I have a ready appliance on RBPi B+ so I will keep it running. If the problem re-occurs I will open a new issue. 

10 x thanks.

**Comment by sparvu** [comment]
Still one question: the proposed patch will do ARM and X86, right ?

**Comment by agentzh** [comment]
@sparvu Yes, it applies to all architectures including x86 though x86 does not require address alignment. I've already committed the patch to git master and will get included in the next ngx_lua and openresty release.

**Pull request closed without merging**
